### ISSUE TITLE
provide users with a warning notice + add a user agent

### ISSUE THREAD

**Issue by hrbrmstr** [jacobkap/boxoffice#1]
http://www.boxofficemojo.com/about/termsofuse.htm is pretty clear that even with their http://www.boxofficemojo.com/robots.txt, Box Office Mojo requires anyone scraping non-robots-restricted areas of the sites to obtain written permission to do so.

The package itself does not violate ToS but the second someone uses it, they are violating the ToS and may end up with fines or worse depending upon the jurisdiction.

Note that The Numbers does not have any ToS and the paths used in the package do not violate the robots.txt rules.

Also, general "rules of scraping" also dictate that any formalized tool for scraping (a.k.a. 'bots') should use a user-agent that identifies the tool and, ideally, the individual. Something like:

    Mozilla/5.0 (compatible; a bot using the R boxoffice package; https://github.com/jacobkap/boxoffice/)

would provide the site owners with enough of a reference to make more informed decisions about not going after individuals using the package (R users tend to not maliciously use code). This would mean either switching from `read_html()` [here](https://github.com/jacobkap/boxoffice/blob/master/R/main_function.R#L63) to `httr::GET()` (which has a `user_agent()` helper function) or saving the `HTTPUserAgent` `option()`, switching it to one in the package and switching it back after the call (some of us set our own on R startup).

**Comment by jacobkap** [comment]
Thanks! I've updated the package so it sends a message when boxofficemojo.com is selected. Do you think it would be better to remove that option entirely?

**Comment by hrbrmstr** [comment]
I don't think so. You aren't doing anything bad (they do allow scraping provided folks ask for permission) so I'd keep it. It's not your fault if folks don't ask for permission, too. The main reason I poked abt this is that many (most) folks aren't even aware there are potential civil/legal issues with scraping and I do what I can to make sure pkg authors aren't even remotely held liable if their users decide to do intentional or unintentional things that violate Terms or robots.txt.
